"""empty message

Revision ID: 69ee764d272c
Revises: f71246012648
Create Date: 2016-06-23 09:49:08.832839

"""

# revision identifiers, used by Alembic.
revision = '69ee764d272c'
down_revision = 'f71246012648'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('mailing_list', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'mailing_list')
    ### end Alembic commands ###
