"""empty message

Revision ID: c1e4bcec397b
Revises: 69ee764d272c
Create Date: 2016-07-22 16:41:34.523934

"""

# revision identifiers, used by Alembic.
revision = 'c1e4bcec397b'
down_revision = '69ee764d272c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('checking_interval', sa.Integer(), nullable=True))
    op.drop_index('document_page_document_id_idx', table_name='document_page')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('document_page_document_id_idx', 'document_page', ['document_id'], unique=False)
    op.drop_column('alert', 'checking_interval')
    ### end Alembic commands ###
