"""empty message

Revision ID: f71246012648
Revises: 15a258b73a77
Create Date: 2016-06-05 17:35:09.408962

"""

# revision identifiers, used by Alembic.
revision = 'f71246012648'
down_revision = '15a258b73a77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('password', sa.String(length=255), server_default='', nullable=False))
    op.add_column('role', sa.Column('reset_password_token', sa.String(length=100), server_default='', nullable=False))
    op.alter_column('role', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'role', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.alter_column('role', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('role', 'reset_password_token')
    op.drop_column('role', 'password')
    op.drop_column('role', 'confirmed_at')
    ### end Alembic commands ###
